import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useState } from "react";
import { Provider } from "react-redux";
import Header from "@components/Header";
import store from "@store/store";
import { CookiesProvider } from "react-cookie";
import "@styles/global.scss";

function MyApp({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <>
      <Head>
        <title>돼지는 여행 중</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Provider store={store}>
        <QueryClientProvider client={queryClient}>
          <CookiesProvider>
            <Header />
            <Component {...pageProps} />
          </CookiesProvider>
        </QueryClientProvider>
      </Provider>
      <footer>
        2022 taei-kang <a href="https://github.com/Tae2u2/travel-pig">github</a>
      </footer>
    </>
  );
}

export default MyApp;
